[project]
name = "fitnessapp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "imageio>=2.36.1",
    "mediapipe>=0.10.14",
    "numpy>=2.2.1",
    "opencv-python>=4.10.0.84",
]
